name: docs
on:
  push:
    branches:
    - main
permissions:
    contents: write
      
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.11"

    - name: Install requirements
      run: |
        pip3 install sphinx_book_theme
    
    - name: Build docs
      run: |
        cd docs
        pip install -r doc_reqs.txt
        make html
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/